name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '11'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v1

      - run: ./gradlew build --no-daemon
        working-directory: ./gradle-plugin
