name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '14'
          cache: 'gradle'

      - uses: gradle/wrapper-validation-action@v1

      - working-directory: ./gradle-plugin
        run: ./gradlew build --no-daemon
