name: Publish

on:
  push:
    branches:
      - master
#    tags:
#      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/ci

      - run: echo "Publish"
