name: Publish

on:
  push:
    branches:
      - master
#    tags:
#      - 'v*'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - run: ls

