name: Publish

on:
  push:
    branches:
      - master
#    tags:
#      - 'v*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/ci.yml

      - run: echo "Publish"
